# Generated by Django 3.2 on 2021-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_publikacji',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
