# Generated by Django 3.2 on 2021-05-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0002_alter_book_data_publikacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='zdjecie',
            field=models.ImageField(upload_to='book_pics'),
        ),
    ]
